server:
  port: 8083
spring:
  application:
    name: purchasecliente
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validete
  flyway:
    baseline-on-migrate: false
    enabled: false  
    locations: classpath:/db/migration
    schemas: public
    default-schema: public 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka